### PR TITLE
refactor!(useWebWorkerFn): export WebWorkerStatus as type instead of enum

### LINKED ISSUE #172: TypeScript error with --isolatedModules flag
The [TypeScript compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html) `--isolatedModules` reports an error:
```
node_modules/@vueuse/core/dist/index.d.ts:492:278 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```
It would be nice if vueuse would not prevent the use of this compiler option.

### PR DESCRIPTION
**Pull request by neelance**
This is to allow use of the TypeScript compiler option --isolatedModules.

Fixes #172

### CODE REVIEW

**Comment by antfu** [comment]
The usage of `const enum` is because `enum` generated code wouldn't be tree-shakeable. Refer https://github.com/microsoft/TypeScript/issues/27604

I don't think it's a good trade-off for this PR.

Maybe we can simply do this:

```ts
export type WorkerStatus = 'PENDING' | 'SUCCESS' | 'RUNNING' | 'ERROR' | 'TIMEOUT_EXPIRED'
```

WDYT?

**Comment by neelance** [comment]
`export type WorkerStatus` sounds good!

**Comment by antfu** [comment]
Would you mind changes the pr addressing that? Thanks

**Comment by neelance** [comment]
Done.

**Comment by neelance** [comment]
Thanks!

**Pull request merged**
