### PR TITLE
feat(templateRef): new function

### PR DESCRIPTION
**Pull request by aa900031**
Make Vue 2 use reactive $refs easy like in Vue 3

### CODE REVIEW

**Comment by antfu** [comment]
I don't quite understand the context here, can you explain a bit? Thanks

**Comment by aa900031** [comment]
For example have a project dependency are:
- vue: 2.6
- @vue/composition-api

Write component with JSX and `useResizeObserver`, in here have wrong to set <div> ref with `$message`, @vue/composition-api doesn't support that 
```ts
import { ref, defineComponent } from '@vue/composition-api'
import { useResizeObserver } from '@vueuse/core'

export default defineComponent({
  setup() {
    const $message = ref<HTMLElement | null>(null)
    useResizeObserver($message, (entries) => {
      const entry = entries[0]
      console.log('changed!');
    })
    
    return () => (
      <div class="container">
        // Not Work!
        <div ref="$message">
          Hi
        </div>
      </div>
    )
  },
})
```

**Comment by antfu** [comment]
Maybe we can have the API looks like this

```js
import { defineComponent } from '@vue/composition-api'
import { templateRef } from '@vueuse/core'

export default defineComponent({
  setup() {
    const message = templateRef('message', null) // Ref<HTMLElement | null>

    useResizeObserver(message, () => { /* ... */ })
    
    return () => <div ref="message">
  },
})
```

WDYT?

**Comment by aa900031** [comment]
It looks great, but that will change implement, that me think how to do it

**Comment by antfu** [comment]
Also would like to have some unit-tests for this as it's really hard to just eye-bowing it. Let me know if you need any help. Thanks

**Comment by aa900031** [comment]
@antfu It's all done, please review thanks

**Comment by antfu** [comment]
Can you check the "Allow edit from maintainers" for this PR? Thanks.

**Comment by aa900031** [comment]
OK 
截圖 2021-01-14 下午11 55 56

**Comment by antfu** [comment]
I have updated the implementation, can you give it a try in your app to see if that matches what you expected? Thanks.

I will update the demo and docs later.

**Comment by aa900031** [comment]
The implementation with `customRef` is amazing, Thanks.
And sorry for my bad demo and docs

**Comment by antfu** [comment]
Not at all, that's a very good contribution (just me being a bit nitpicking about the overall consistency) Thank you 👍

**Comment by aa900031** [comment]
It's right to overall consistency.
Thank you for the code, I learn a lot

**Comment by antfu** [comment]
Thanks!

**Pull request merged**
